//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.488
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace uComponents.DataTypes.DataTypeGrid.Configuration {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class DtgConfiguration {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal DtgConfiguration() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("uComponents.Core.DataTypes.DataTypeGrid.Configuration.DtgConfiguration", typeof(DtgConfiguration).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;DataTypeGrid&gt;
        ///  &lt;CompatibleDataTypes&gt;
        ///    &lt;!-- Label --&gt;
        ///    &lt;add guid=&quot;6c738306-4c17-4d88-b9bd-6546f3771597&quot;/&gt;
        ///    &lt;!-- Numeric --&gt;
        ///    &lt;add guid=&quot;1413afcb-d19a-4173-8e9a-68288d2a73b8&quot;/&gt;
        ///    &lt;!-- Simple Editor --&gt;
        ///    &lt;add guid=&quot;60b7dabf-99cd-41eb-b8e9-4d2e669bbde9&quot;/&gt;
        ///    &lt;!-- Textstring --&gt;
        ///    &lt;add guid=&quot;ec15c1e5-9d90-422a-aa52-4f7622c63bea&quot;/&gt;
        ///    &lt;!-- Media Picker --&gt;
        ///    &lt;add guid=&quot;ead69342-f06d-4253-83ac-28000225583b&quot;/&gt;
        ///    &lt;!-- Approved Color --&gt;
        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string DataTypeGrid {
            get {
                return ResourceManager.GetString("DataTypeGrid", resourceCulture);
            }
        }
    }
}
